api_version = "2025-04"

[[extensions]]
name = "checkout-enhancements"
handle = "checkout-enhancements"
type = "ui_extension"

[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./src/Checkout.tsx"

[extensions.capabilities]
api_access = true
