api_version = "2025-07"
uid = "67a7e6c9-2b73-442a-2b5b-d2748e4915e2fb2a58e4"

[[extensions]]
name = "checkout-enhancements"
handle = "checkout-enhancements"
type = "ui_extension"

[[extensions.targeting]]
target = "purchase.checkout.contact.render-after"
module = "./src/Checkout.tsx"

[extensions.capabilities]
api_access = true
